# Generated by Django 4.2.7 on 2025-01-27 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Número de capacitor')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KVARValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='KVAR')),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Voltaje')),
                ('amperage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amperaje nominal (A)')),
            ],
            options={
                'verbose_name': 'Valor KVAR',
                'verbose_name_plural': 'Valores KVAR',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de ubicación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_configured', models.BooleanField(default=False, verbose_name='Configuración completada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plc_address.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plc_address.empresa')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plc_address.sector')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_current', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Corriente medida (A)')),
                ('measurement_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('capacitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='plc_address.capacitor')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_io', models.CharField(choices=[('DI', 'Digital Input'), ('DO', 'Digital Output'), ('AI', 'Analog Input'), ('AO', 'Analog Output'), ('RTD_IN', 'RTD Input'), ('RTD_OUT', 'RTD Output')], max_length=10)),
                ('direccion_plc', models.CharField(max_length=50)),
                ('slot', models.IntegerField()),
                ('bastidor', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('numero_modulo', models.IntegerField()),
                ('numero_entrada', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='plc_address.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Contactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Número de contactor')),
                ('is_configured', models.BooleanField(default=False, verbose_name='Configuración completada')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactors', to='plc_address.location')),
            ],
        ),
        migrations.AddField(
            model_name='capacitor',
            name='contactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitors', to='plc_address.contactor'),
        ),
        migrations.AddField(
            model_name='capacitor',
            name='kvar_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plc_address.kvarvalue', verbose_name='Valor KVAR'),
        ),
    ]
