# Generated by Django 4.2.7 on 2025-01-23 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plc_address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='empresa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='plc_address.empresa'),
            preserve_default=False,
        ),
    ]
