# Generated by Django 4.2.3 on 2025-01-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plc_address', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
