# Generated by Django 4.2.3 on 2025-01-22 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plc_address', '0005_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plc_address.empresa'),
        ),
    ]
